# Generated by Django 4.2.7 on 2024-03-11 02:35

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_type',
            name='employee_type',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras.', regex='^[a-zA-Z]*$')], verbose_name='Tipo Empleado'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 3, 10))], verbose_name='Fecha Entrada'),
        ),
        migrations.AlterField(
            model_name='output',
            name='output_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 3, 10))], verbose_name='Fecha Salida'),
        ),
        migrations.AlterField(
            model_name='product_request',
            name='deliver_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 3, 10))], verbose_name='Fecha Entrega'),
        ),
        migrations.AlterField(
            model_name='request_status',
            name='status',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras.', regex='^[a-zA-Z]*$')], verbose_name='Estado de soliciutd'),
        ),
        migrations.AlterField(
            model_name='suplier',
            name='phone',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(message='Formato de teléfono no válido. Debe tener entre 10 y 15 dígitos.', regex='^[0-9]{10,15}$')], verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='supplier_status',
            name='status_s',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras.', regex='^[a-zA-Z]*$')], verbose_name='Estado Proveedor'),
        ),
    ]
