# Generated by Django 4.2.7 on 2023-11-18 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_entry_cod_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='output',
            name='cod_output',
        ),
    ]
