# Generated by Django 4.2.7 on 2023-11-18 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_output_cod_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_request',
            name='id_request_p',
        ),
    ]
