# Generated by Django 4.2.7 on 2023-11-18 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_product_request_id_request_p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_time',
            name='cod_work_time',
        ),
    ]
