# Generated by Django 4.2.7 on 2024-03-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_entry_entry_date_alter_output_output_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='detail',
            field=models.CharField(max_length=200, verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='output',
            name='output_date',
            field=models.DateTimeField(verbose_name='Fecha Salida'),
        ),
    ]
