# Generated by Django 4.2.7 on 2024-03-16 21:04

import datetime
import django.core.validators
from django.db import migrations, models
import inventario.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_entry_detail_alter_output_output_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='output_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 3, 16))], verbose_name='Fecha Salida'),
        ),
        migrations.AlterField(
            model_name='product_request',
            name='deliver_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 3, 16))], verbose_name='Fecha Entrega'),
        ),
        migrations.AlterField(
            model_name='suplier',
            name='nit',
            field=models.PositiveIntegerField(validators=[inventario.models.validate_nit], verbose_name='Nit'),
        ),
    ]
