# Generated by Django 4.2.7 on 2024-03-18 20:13

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_output_output_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 3, 18))], verbose_name='Fecha Entrada'),
        ),
        migrations.AlterField(
            model_name='output',
            name='output_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 3, 18))], verbose_name='Fecha Salida'),
        ),
        migrations.AlterField(
            model_name='product_request',
            name='deliver_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 3, 18))], verbose_name='Fecha Entrega'),
        ),
    ]
