# Generated by Django 4.2.7 on 2023-11-08 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_city', models.PositiveIntegerField(verbose_name='Cod Ciudad')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'ciudad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Client_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_client_type', models.PositiveIntegerField(verbose_name='Cod Tipo Cliente')),
                ('client_type', models.CharField(max_length=50, verbose_name='Tipo Cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Cliente',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Domicile_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_status_d', models.PositiveIntegerField(verbose_name='Cod Estado D')),
                ('statud_d', models.CharField(max_length=20, verbose_name='Estado D')),
            ],
            options={
                'verbose_name': 'Estado Domicilio',
                'verbose_name_plural': 'Estado Domicilios',
                'db_table': 'estado_domicilio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_employee', models.PositiveIntegerField(verbose_name='Id Empleado')),
                ('employee', models.CharField(max_length=50, verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Employee_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_t_e', models.PositiveIntegerField(verbose_name='Cod Tipo Empleado')),
                ('employee_type', models.CharField(max_length=20, verbose_name='Tipo Empleado')),
            ],
            options={
                'verbose_name': 'Tipo Empleado',
                'verbose_name_plural': 'Tipo Empleados',
                'db_table': 'tipo_empleado',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_entry', models.PositiveIntegerField(verbose_name='Codigo Entrada')),
                ('amount', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('detail', models.CharField(max_length=50, verbose_name='Detalle')),
                ('entry_date', models.DateField(verbose_name='Fecha Entrada')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'db_table': 'entrada',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.PositiveIntegerField(verbose_name='Id_Producto')),
                ('product_name', models.CharField(max_length=50, verbose_name='Nombre Producto')),
                ('product_brand', models.CharField(max_length=50, verbose_name='Marca Producto')),
                ('product_amount', models.PositiveIntegerField(verbose_name='Cantidad Producto')),
                ('fabrication_date', models.DateField(verbose_name='Fecha Fabricación')),
                ('product_color', models.CharField(max_length=50, verbose_name='Color Producto')),
                ('promotion', models.CharField(max_length=50, verbose_name='Promoción')),
                ('discount', models.PositiveIntegerField(verbose_name='Descuento')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_category_p', models.PositiveIntegerField(verbose_name='Cod Categoria P')),
                ('category', models.CharField(max_length=50, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria Producto',
                'verbose_name_plural': 'Categoria Productos',
                'db_table': 'categoria_producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_request_p', models.PositiveIntegerField(verbose_name='Id Solicitud P')),
                ('price_deliver', models.PositiveIntegerField(verbose_name='Precio Pedido')),
                ('deliver_date', models.DateTimeField(verbose_name='Fecha Entrega')),
            ],
            options={
                'verbose_name': 'Solicitud Producto',
                'verbose_name_plural': 'Solicitudes Productos',
                'db_table': 'solicitud_producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_status_p', models.PositiveIntegerField(verbose_name='Cod Estado P')),
                ('status', models.CharField(max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Estado Producto',
                'verbose_name_plural': 'Estado productos',
                'db_table': 'estado_producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Request_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_status_s', models.PositiveIntegerField(verbose_name='Cod Estado S')),
                ('status', models.CharField(max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Estado Solicitud',
                'verbose_name_plural': 'Estado Solicitudes',
                'db_table': 'estado_solicitud',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Supplier_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_status', models.PositiveIntegerField(verbose_name='Cod Proveedor')),
                ('status_s', models.CharField(max_length=50, verbose_name='Estado P')),
            ],
            options={
                'verbose_name': 'Estado Proveedor',
                'verbose_name_plural': 'Estado Proveedores',
                'db_table': 'estado_proveedor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Work_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_work_time', models.PositiveIntegerField(verbose_name='Cod Tiempo Trabajo')),
                ('timetable', models.CharField(max_length=20, verbose_name='Horario')),
                ('days', models.CharField(max_length=20, verbose_name='Dias')),
            ],
            options={
                'verbose_name': 'Tiempo Trabajo',
                'verbose_name_plural': 'Tiempos Trabajo',
                'db_table': 'tiempo_trabajo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Suplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_supplier', models.PositiveIntegerField(verbose_name='Id Proveedor')),
                ('nit', models.PositiveIntegerField(verbose_name='Nit')),
                ('legal_representative_name', models.CharField(max_length=50, verbose_name='Nombre Representante Legal')),
                ('phone', models.PositiveIntegerField(verbose_name='Telefono')),
                ('cod_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city')),
                ('cod_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supplier_status')),
                ('id_solicitud_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product_request')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sale', models.PositiveIntegerField(verbose_name='Id Venta')),
                ('sale_date', models.DateField(verbose_name='Fecha Venta')),
                ('sale_amount', models.PositiveIntegerField(verbose_name='Cantidad Venta')),
                ('sale_send', models.CharField(max_length=50, verbose_name='Envio Venta')),
                ('unit_value', models.PositiveIntegerField(verbose_name='Valor Unitario')),
                ('discount', models.PositiveIntegerField(verbose_name='Descuento')),
                ('vat', models.PositiveIntegerField(verbose_name='IVA')),
                ('subtotal', models.PositiveIntegerField(verbose_name='Subtotal')),
                ('total', models.PositiveIntegerField(verbose_name='Total')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='product_request',
            name='cod_status_s',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.request_status'),
        ),
        migrations.AddField(
            model_name='product_request',
            name='id_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee'),
        ),
        migrations.AddField(
            model_name='product',
            name='cod_Status_p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product_status'),
        ),
        migrations.AddField(
            model_name='product',
            name='cod_category_p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product_category'),
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_output', models.PositiveIntegerField(verbose_name='Cod Salida')),
                ('output_amount', models.IntegerField(verbose_name='Cantidad Salida')),
                ('detail', models.CharField(max_length=50, verbose_name='Detalle')),
                ('output_date', models.DateTimeField(verbose_name='Fecha Salida')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'verbose_name': 'Salida',
                'verbose_name_plural': 'Salidas',
                'db_table': 'salida',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_inventory', models.PositiveIntegerField(verbose_name='Id Inventario')),
                ('stock', models.CharField(max_length=50, verbose_name='Stock')),
                ('inventory_amount', models.PositiveIntegerField(verbose_name='Cantidad Inventario')),
                ('minimum_amount', models.PositiveIntegerField(verbose_name='Cantidad Minima')),
                ('cod_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entry')),
                ('cod_output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.output')),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Domicile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_domicile', models.PositiveIntegerField(verbose_name='Id Domicilio')),
                ('guide_number', models.PositiveIntegerField(verbose_name='Numero Guia')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('direction', models.CharField(max_length=50, verbose_name='Dirección')),
                ('cod_status_domicile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.domicile_status')),
                ('id_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sale')),
            ],
            options={
                'verbose_name': 'Domicilio',
                'verbose_name_plural': 'Domicilios',
                'db_table': 'domicilio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Company_Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_nit', models.PositiveIntegerField(verbose_name='Nit Empresa')),
                ('date_domicile', models.DateField(verbose_name='Fecha Entrega')),
                ('id_domicile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.domicile')),
            ],
            options={
                'verbose_name': 'Empresa Trasportadora',
                'verbose_name_plural': 'Empresas Transportadoras',
                'db_table': 'empresa_transportadora',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_activities', models.PositiveIntegerField(verbose_name='Cod_Actividades')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('state', models.CharField(max_length=50, verbose_name='Estado')),
                ('time_dt', models.DateTimeField(verbose_name='Tiempo Dt')),
                ('cod_t_e', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee_type')),
            ],
            options={
                'verbose_name': 'Actividades',
                'verbose_name_plural': 'Actividades',
                'db_table': 'actividades',
                'ordering': ['id'],
            },
        ),
    ]
