# Generated by Django 4.2.7 on 2023-11-29 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Categoria producto')),
            ],
            options={
                'verbose_name': 'Categoria Producto',
                'verbose_name_plural': 'Categoria Productos',
                'db_table': 'categoria_producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, verbose_name='Estado producto')),
            ],
            options={
                'verbose_name': 'Estado Producto',
                'verbose_name_plural': 'Estado productos',
                'db_table': 'estado_producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(verbose_name='Fecha Venta')),
                ('sale_amount', models.PositiveIntegerField(verbose_name='Cantidad Venta')),
                ('sale_send', models.CharField(max_length=50, verbose_name='Envio Venta')),
                ('unit_value', models.PositiveIntegerField(verbose_name='Valor Unitario')),
                ('discount', models.PositiveIntegerField(verbose_name='Descuento')),
                ('vat', models.PositiveIntegerField(verbose_name='IVA')),
                ('subtotal', models.PositiveIntegerField(verbose_name='Subtotal')),
                ('total', models.PositiveIntegerField(verbose_name='Total')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Nombre Producto')),
                ('product_brand', models.CharField(max_length=50, verbose_name='Marca Producto')),
                ('product_amount', models.PositiveIntegerField(verbose_name='Cantidad Producto')),
                ('fabrication_date', models.DateField(verbose_name='Fecha Fabricación')),
                ('product_color', models.CharField(max_length=50, verbose_name='Color Producto')),
                ('promotion', models.CharField(max_length=50, verbose_name='Promoción')),
                ('discount', models.PositiveIntegerField(verbose_name='Descuento')),
                ('Status_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.product_status', verbose_name='Estado producto')),
                ('category_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.product_category', verbose_name='Categoria producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['id'],
            },
        ),
    ]
