# Generated by Django 4.2.7 on 2023-11-18 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sale',
        ),
    ]
