# Generated by Django 4.2.7 on 2023-11-17 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['id'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.RemoveField(
            model_name='sale',
            name='id_sale',
        ),
        migrations.AlterModelTable(
            name='sale',
            table='venta',
        ),
    ]
