# Generated by Django 4.2.7 on 2024-03-11 02:35

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fabrication_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 3, 10))], verbose_name='Fecha Fabricación'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_brand',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras.', regex='^[a-zA-Z]*$')], verbose_name='Marca Producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras.', regex='^[a-zA-Z]*$')], verbose_name='Nombre Producto'),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='category',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras.', regex='^[a-zA-Z]*$')], verbose_name='Categoria producto'),
        ),
        migrations.AlterField(
            model_name='product_status',
            name='status',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras.', regex='^[a-zA-Z]*$')], verbose_name='Estado producto'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 3, 10))], verbose_name='Fecha Venta'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='subtotal',
            field=models.PositiveIntegerField(editable=False, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.PositiveIntegerField(editable=False, verbose_name='Total'),
        ),
    ]
