# Generated by Django 4.2.7 on 2024-03-11 02:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_alter_product_fabrication_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=100)], verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='vat',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=100)], verbose_name='IVA'),
        ),
    ]
