# Generated by Django 4.2.7 on 2023-11-18 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domicilios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domicile',
            name='guide_number',
        ),
    ]
