# Generated by Django 4.2.7 on 2024-03-11 02:35

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domicilios', '0003_delete_reportdefinition_delete_reportrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras.', regex='^[a-zA-Z]*$')], verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='company_transportation',
            name='date_domicile',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 3, 10))], verbose_name='Fecha Entrega'),
        ),
        migrations.AlterField(
            model_name='domicile',
            name='date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 3, 10))], verbose_name='Fecha'),
        ),
    ]
