# Generated by Django 4.2.7 on 2024-03-16 20:07

from django.db import migrations, models
import domicilios.models


class Migration(migrations.Migration):

    dependencies = [
        ('domicilios', '0006_alter_company_transportation_date_domicile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_transportation',
            name='company_nit',
            field=models.PositiveIntegerField(validators=[domicilios.models.validate_nit], verbose_name='Nit Empresa'),
        ),
    ]
