# Generated by Django 4.2.7 on 2024-03-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domicilios', '0007_alter_company_transportation_company_nit'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_transportation',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Empresa'),
        ),
    ]
